### ISSUE TITLE
missing h

### ISSUE THREAD

**Issue by 369Martin369** [milnepe/helium-mkr1310-node#1]
please teach me how to get those .h's. thanks

#include <MKRWAN.h>
#include <forcedClimate.h>
#include "ArduinoLowPower.h"

**Comment by milnepe** [comment]
These are all libraries available through the [Arduino IDE](https://www.arduino.cc/en/software). Just open the Library Manager, search for the library, then install it into the IDE. You can then build the firmware and flash the MKR1310 from the IDE.
