### ISSUE TITLE
the "issue" is presumably me

### ISSUE THREAD

**Issue by awkonradi** [milnepe/helium-mkr1310-node#2]
Hi Peter, I have not been able to replicate the performance of your node.  Using your sketch, my serial monitor reports nothing after the Device EUI.  My Helium console reports a Join Request and Join Accept, but nothing more.  I am using SEND_INTERVAL 5.  My hardware executes the LoraSendAndReceive example including uplinks and acknowledgements.  I am a novice, and I would be grateful if you could help me troubleshoot this, but I recognize you are a busy man.  Best, Andrei awkonradi@yahoo.com

**Comment by milnepe** [comment]
Hi Andrei,

I just updated all my libraries (Arduino 2.0.3), cloned a fresh copy of the repo and set the APP_EUI and APP_KEY from my Helium account and re-flashed the MKR1310 and the message was sent perfectly - here is the serial monitor output - note Firmware version.

Begin debugging...
Firmware version: ARD-078 1.2.3
Device EUI: XXXXXXX
Readings int16_t: 608 0 2010 4759 9919 1
Readings byte array: 0 0 7 DA 12 97 26 BF 0 1 
Message sent correctly!

I also checked on the Helium console and the IFTTT message was received on my mobile.

There is a detailed write up of the project on the OKdo Knowledge Hub which might help you:
https://www.okdo.com/getting-started/get-started-with-helium-network/

If you are not running this code then please post to the Arduino forum for help.

**Comment by awkonradi** [comment]
Hi Peter,

Thank you.  My device just needed multiple attempts to join Helium.  I added the "Something went wrong; are you indoor? Move near a window and retry" instruction, which is in the LoraSendAndReceive example, to your code, to cue me to restart.  Now my device is uploading data to a Google sheet.  Yes, I found you after I found the OKdo project.

Best,

Andrei
